apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-q7k3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jjqm-tenant/rhtap-demo-app/hacbs-test-project-q7k3@sha256:e0253734980c2411c098dc23d9997ca8a7bc5afabc46d736dc1f24ba6f361236
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
